version: '2'

services:
  data:
    build: ./data
    image: ${CONTAINER_PREFIX}.data
    container_name: ${CONTAINER_PREFIX}.data
    volumes:
      - ${PROJECTS_FOLDER}:/var/www/html
    restart: always
    networks:
      - backend

  db-data:
    image: ${CONTAINER_PREFIX}.data
    container_name: ${CONTAINER_PREFIX}.db-data
    volumes:
      - ${DATABASE_FOLDER}:/var/lib/mysql
    restart: always
    networks:
      - backend

  mysql:
    image: mysql
    container_name: ${CONTAINER_PREFIX}.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db-data
    volumes_from:
      - db-data
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_PREFIX}.phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: always
    networks:
      - backend
      - frontend

  php:
    build:
      context: ./php7-apache
      args:
        TIMEZONE: ${TIMEZONE}
    image: ${CONTAINER_PREFIX}.php
    container_name: ${CONTAINER_PREFIX}.php
    depends_on:
      - data
    volumes_from:
      - data
    links:
      - mysql
    volumes:
      #:ro option makes the mount read-only.
      - ${DOCKER_FILES}/php7-apache/php/php.ini:/usr/local/etc/php/php.ini
      - ${DOCKER_FILES}/php7-apache/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf:ro
      - ${DOCKER_FILES}/php7-apache/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf:ro
    ports:
      - ${APACHE_PORT}:80
    restart: always
    networks:
      - backend

networks:
  frontend:
  backend: